name: Backend CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3    # клонируем репозиторий

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'   # версия ASP.NET Core

      - name: Restore
        run: dotnet restore ./backend/src/SystemControl.Api/SystemControl.Api.csproj

      - name: Build
        run: dotnet build --no-restore ./backend/src/SystemControl.Api/SystemControl.Api.csproj

      # - name: Test
      # run: dotnet test ./backend/tests
